# fly.toml app configuration file generated for my-buddy on 2025-07-21T11:12:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-buddy'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [[http_service.checks]]
    interval = "30s"
    timeout  = "10s"
    method   = "GET"
    path     = "/healthz"

[[vm]]
  memory = "256mb"
  cpu_kind = 'shared'
  cpus = 1
