name: Deploy to Fly
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions@v1
        with:
          args: "deploy --remote-only --detach"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          BOT_TOKEN:     ${{ secrets.BOT_TOKEN }}
          OPENAI_API_KEY:${{ secrets.OPENAI_API_KEY }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}